# Generated by Django 4.1.3 on 2024-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_address',
            field=models.URLField(default='https://maps.google.com'),
            preserve_default=False,
        ),
    ]
